[tool.poetry]
name = "rl-robust"
version = "0.1.0"
description = "Robust Reinforcement Learning Algorithms"
authors = ["Your Name <your.email@example.com>"]

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.24.0"
pydantic = "^2.0.0"
polars = "^0.19.0"
pyyaml = "^6.0.0"
matplotlib = "^3.7.0"
scipy = "^1.10.0"
joblib = "^1.3.0"

[tool.poetry.dev-dependencies]
pytest = "^7.0.0"
black = "^23.0.0"
isort = "^5.12.0"
mypy = "^1.5.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
